all:
  vars:
    ansible_user: dev
    ansible_password: dev
    ansible_become_pass: dev
  children:
    atest_win:
      hosts:
        192.168.160.185:
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: basic
        ansible_port: 5985
    atest_nix:
      hosts:
        192.168.160.187:
      vars:
        ansible_connection: ssh

